# fly.toml app configuration file generated for pokedextestproject on 2023-07-18T17:20:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedextestproject"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"
	
[[services]]
  http_checks = []
  internal_port = 8080

  processes = ["app"]
  
  
 [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"