name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      PORT: 5000
      FLYCTL_INSTALL: /home/runner/.fly
      PATH: ${{ env.FLYCTL_INSTALL }}/bin:${{ env.PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh
      - name: Verify flyctl installation
        run: flyctl version
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN}}
